name: benchmark ci
on: [push]
jobs:
  build:
    name: 'tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.7.12
      - shell: bash
        run: make setup.env